name: Build Push and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java  
      uses: actions/setup-java@v5
      with:
          distribution: 'temurin' 
          java-version: '21'

    - name: Build Jar
      run: ./mvnw clean package -D skipTests

    - name: Login Dockerhub
      uses: docker/login-action@v3
      with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.TOKEN}}


    - name: Build Docker Image 
      run : docker build -t ${{secrets.DOCKERHUB_USERNAME}}/springboot:latest

    - name : Push Image to Docker hub 
      run :  docker push ${{secrets.DOCKERHUB_USERNAME}}/springboot:latest


    - name : SSH into machine 
      uses: appleboy/ssh-action@v1
      with:
          host: ${{secrets.EC2_HOST}}
          user: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          script:
            docker stop spring-demo || true
            docker rm spring-demo || true
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/springboot:latest
            docker run --name spring-demo -d -p 8080:8080 ${{secrets.DOCKERHUB_USERNAME}}/springboot:latest
            





      
